version: "3.7"

services:
  mysql:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: Pass1234!
      MYSQL_ROOT_PASSWORD: Pass1234!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:

networks:
  dev:
    driver: bridge
# server connection-string jdbc:mysql://localhost:3306/databasename
# If Error: ER_NOT_SUPPORTED_AUTH_MODE, delete and create again the database using MySQL Workbench
