version: '3.7'

services:

  redis:
    image: redis
    container_name: Redis_Cache
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev

volumes:
  redis-data:
    driver: local

networks:
  dev:
    driver: bridge